config/routes.rb
Heliosystem::Engine.routes.draw do
  
  post 'sessions/create', as: 'create_session'
  get 'sessions/destroy', as: 'destroy_session'
  post 'users' => 'users#create', as: 'users'

  root to: 'static#welcome'

  resources :universes, path: '/' do

    resources :people
    resources :subfields, except: [:show, :new]
    resources :subrelations, except: [:show, :new]
    resources :settings, except: [:show, :new]
    resources :tags

    resources :organizations, path: '/o' do
      resources :accounts
      resources :pages
      resources :people
      resources :settings, except: [:show, :new]
      resources :tags
      resources :timeclocks do
        member do
          get 'punches'
          post 'punch'  
        end
      end
      
    end
  end



end

app/models/concerns/heliosystem/customizable.rb
# CUSTOMIZABLE MODELS
# To make a model customizable:
# 1. Include this concern in to your model: `include Customizable`
# 2. Add `subfield_values: {}, subrelation_pairs: {}` to the list of
#    permitted parameters in your controller
# 3. Because you can't create values/pairs without the parent model existing in
#    the database, you have to do a little workaround in your `create` action.
#    Take a look at `PeopleController#create` for an example.
# 4. Add the `heliosystem/partials/customFormFields` partial to your form. It takes
#    3 locals: `form` (the form object), `model`, the object you're working with,
#    and `app`, the name of the app you're working with.
# 5. Add your app to Heliosystem::Subfield::APPS & Heliosystem::Subrelation::APPS

require 'active_support/concern'

module Heliosystem
  module Customizable
    extend ActiveSupport::Concern

    included do
      has_many :subfield_values, as: :app
      has_many :parent_subrelation_pairs, as: :parent
      has_many :child_subrelation_pairs, as: :child
    end

    def customizable_name
      @customizable_name ||= self.class.to_s.split('::').last.downcase
    end

    def subfield_values=(attrs)
      attrs.each do |k,v|
        if (sf = universe.subfields.find_by(label: k, app: customizable_name)).present?
          sv = subfield_values.where(subfield_id: sf.id).first_or_create
          sv.value = v.to_s
          sv.save
        end
      end if attrs.present?
    end

    def subrelation_pairs
      universe.subrelations.where(parent: customizable_name).map {|sr| sr.subrelation_pairs.where(subrelation_id: sr.id).first_or_create }
    end

    def subrelation_pairs=(attrs)
      attrs.each do |k,v|
        if (sr = universe.subrelations.find_by(label: k, parent: customizable_name)).present?
          pairs = sr.subrelation_pairs
          entities = v.filter(&:present?).map{ |eid| universe.send(sr.child.pluralize.to_sym).find(eid)}
          # remove unnecessary entity pairs
          pairs.each do |p|
            p.delete unless entities.include?(p.child)
          end
          # create missing entity pairs
          entities.each do |et|
            if !pairs.map(&:child).include?(et)
              sr.subrelation_pairs.create(child: et, parent: self)
            end
          end
        end
      end if attrs.present?
    end

  end
end

app/models/concerns/heliosystem/taggable.rb
# TAGGABLE MODELS
# To make a model taggable:
# 1. Include this concern in to your model: `include Customizable`
# 2. Add `tag_ids: []` to the list of permitted parameters in your controller
# 3. Add the `heliosystem/partials/taggableFields` partial to your form. It
#    takes 2 locals: `form` (the form object), and `model`, the object
#    you're working with.

require 'active_support/concern'

module Heliosystem
  module Taggable
    extend ActiveSupport::Concern

    included do
      has_many :taggings, as: :taggable
      has_many :tags, through: :taggings
    end
  end
end

app/models/heliosystem/account.rb
require 'money'

module Heliosystem
  class Account < ApplicationRecord
    extend FriendlyId
    friendly_id :code, use: :slugged
    include Customizable
    include Taggable
    belongs_to :organization
    belongs_to :parent, class_name: 'Account', optional: true, inverse_of: :children
    has_many :children, class_name: 'Account', dependent: :destroy, inverse_of: :parent, foreign_key: 'parent_id'
    before_save :update_parent_balances

    def balance
      Money.new(balance_cents, 'usd')
    end

    def balance=(val)
      self.balance_cents = BigDecimal(val) * 100
    end

    def depth
      (parent ? parent.depth + 1 : 0)
    end

    def universe
      organization.universe
    end

    def subcode
      code.split(organization.setting('accounts.separator') || '.').last
    end

    private

    def update_parent_balances
      return unless parent && balance_cents_changed?
      puts "Updating balance for #{parent.name}"
      delta = changes['balance_cents'][1] - changes['balance_cents'][0]
      parent.balance_cents += delta
      parent.save
    end
  end
end

app/models/heliosystem/application_record.rb
module Heliosystem
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/heliosystem/membership.rb
module Heliosystem
  class Membership < ApplicationRecord
    belongs_to :organization
    belongs_to :person
  end
end

app/models/heliosystem/organization.rb
module Heliosystem
  class Organization < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    belongs_to :universe

    has_many :accounts
    has_many :memberships, dependent: :destroy
    has_many :pages
    has_many :people, through: :memberships
    has_many :settings
    has_many :tags
    has_many :timeclocks

    def setting(key)
      if s = settings.where(key: key).first
        s.value
      else
        universe.setting(key)
      end
    end

  end
end

app/models/heliosystem/page.rb
module Heliosystem
  class Page < ApplicationRecord
    include Customizable
    include Taggable
    belongs_to :organization

    def name
      title
    end

    def universe
      organization.universe
    end
  end
end

app/models/heliosystem/person.rb
module Heliosystem
  class Person < ApplicationRecord
    include Customizable
    include Taggable
    belongs_to :universe
    belongs_to :user
    has_many :memberships
    has_many :organizations, through: :memberships
    has_many :timepunches
    accepts_nested_attributes_for :user

    def name
      user.first_name + ' ' + user.last_name
    end
  end
end

app/models/heliosystem/setting.rb
module Heliosystem
  class Setting < ApplicationRecord

    def organization
      Organization.find(organization_id) if organization_id
    end

    def universe
      organization.universe if organization
      Universe.find(universe_id)
    end

    def container
      organization || universe
    end
  end
end

app/models/heliosystem/subfield.rb
module Heliosystem
  class Subfield < ApplicationRecord
    belongs_to :universe
    has_many :subfield_values, dependent: :destroy

    APPS = %w{person account timeclock page}
    FORMATS = %w(boolean string email url tel password text integer decimal datetime date time select)
  end
end

app/models/heliosystem/subfield_value.rb
module Heliosystem
  class SubfieldValue < ApplicationRecord
    belongs_to :subfield
  end
end

app/models/heliosystem/subrelation.rb
module Heliosystem
  class Subrelation < ApplicationRecord
    belongs_to :universe
    has_many :subrelation_pairs, dependent: :destroy

    APPS = %w{person event timeclock page}
    FORMATS = %w{one-to-one one-to-many many-to-many}
  end
end

app/models/heliosystem/subrelation_pair.rb
module Heliosystem
  class SubrelationPair < ApplicationRecord
    belongs_to :subrelation
    belongs_to :parent, polymorphic: true
    belongs_to :child, polymorphic: true
  end
end

app/models/heliosystem/tag.rb
module Heliosystem
  class Tag < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    has_many :taggings
    belongs_to :universe
    belongs_to :organization, optional: true

    def taggables
      taggings.map(&:taggable)
    end
  end
end

app/models/heliosystem/tagging.rb
module Heliosystem
  class Tagging < ApplicationRecord
    belongs_to :tag
    belongs_to :taggable, polymorphic: true
  end
end

app/models/heliosystem/timeclock.rb
module Heliosystem
  class Timeclock < ApplicationRecord
    include Customizable
    include Taggable
    belongs_to :organization
    has_many :timepunches

    def hours
      timepunches.closed.map(&:hours).reduce(0) { |v, a| a + v }
    end

    def universe
      organization.universe
    end
  end
end

app/models/heliosystem/timepunch.rb
module Heliosystem
  class Timepunch < ApplicationRecord
    belongs_to :timeclock
    belongs_to :person

    scope :open, -> { where(end_at: nil) }
    scope :closed, -> { where.not(end_at: nil) }

    def hours
      return nil unless end_at.present?
      ((end_at - start_at) / 60 / 60 * 4).round / 4.0
    end
  end
end

app/models/heliosystem/universe.rb
module Heliosystem
  class Universe < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    belongs_to :owner, class_name: "User"
    has_many :subfields
    has_many :subrelations
    has_many :people
    has_many :organizations
    has_many :settings
    has_many :tags
    has_many :timeclocks, through: :organizations

    def users
      User.where(id: owner_id)
    end

    def top_level_tags
      tags.where(organization_id: nil)
    end

    def admins
      people.where(admin: true)
    end

    def owner_candidates
      (User.where(id: owner_id).all + admins.map(&:user)).uniq
    end

    def person_for(user)
      if user
        people.find_by(user_id: user.id)
      else
        nil
      end
    end

    def setting(key)
      if s = settings.where(key: key).first
        s.value
      else
        nil
      end
    end
  end
end

app/models/heliosystem/user.rb
module Heliosystem
  class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    has_many :people
    has_many :universes, through: :people

    def owned_universes
      Universe.where(owner_id: id)
    end

    def name
      first_name + ' ' + last_name
    end
  end
end

app/controllers/heliosystem/accounts_controller.rb
require_dependency "heliosystem/application_controller"

module Heliosystem
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    before_action :set_breadcrumbs

    # GET /accounts
    def index
	    @accounts = current_organization.accounts.where(parent_id: nil)
    end

    # GET /accounts/1
    def show
    end

    # GET /accounts/new
    def new
	    @account = current_organization.accounts.build
    end

    # GET /accounts/1/edit
    def edit
    end

    # POST /accounts
    def create
      @account = current_organization.accounts.build(account_params)
      @person.assign_attributes(person_params.except(:subfield_values, :subrelation_pairs))

      if @account.parent
        @account.code = @account.parent.code + (current_organization.setting('accounts.separator') || '.') + @account.code
      end

      if @account.save
        @account.subfield_values = sv
        @account.subrelation_pairs = sp
        @account.save
        redirect_to [current_universe, current_organization, @account], notice: 'Account was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /accounts/1
    def update
      @account.update_attributes(account_params)
      if @account.parent
        puts 'doing that thing'
        @account.code = @account.parent.code + (@account.organization.setting('accounts.separator') || '.') + @account.code
      end
      if @account.save
        redirect_to [current_universe, current_organization, @account], notice: 'Account was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /accounts/1
    def destroy
      @account.destroy
      redirect_to universe_organization_accounts_path(universe_id: current_universe.slug, organization_id: current_organization.slug), notice: 'Account was successfully destroyed.'
    end

    private
      def set_breadcrumbs
        @breadcrumbs << [current_universe, current_universe.name]
        @breadcrumbs << [[current_universe, current_organization], current_organization.name]
        @breadcrumbs << [universe_organization_accounts_path(current_universe, organization_id: current_organization.slug), 'Accounts']
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_account
	      @account = current_organization.accounts.friendly.find(params[:id])
        @breadcrumbs << [ [current_universe, current_organization, @account], @account.name] if @account.id
      end

      # Only allow a trusted parameter "white list" through.
      def account_params
        params.require(:account).permit(:name, :code, :balance, :parent_id, subfield_values: {}, subrelation_pairs: {}, tag_ids: [])
      end
  end
end

app/views/heliosystem/partials/_actionbar.html.erb
<% if current_user %>
  <section class="actionbar">
    <% if current_universe %>
      <%= action_link current_universe, icon('home'), "#{current_universe.name} Home", current_universe.color %>
      <% if current_organization %>
        <%= render(partial: 'heliosystem/partials/orgAppsNavActions') %>
      <% else %>
        <%= action_link universe_people_path(current_universe), icon('users'), "People", current_universe.color %>
        <%= action_link universe_tags_path(current_universe), icon('tags'), "Tags", current_universe.color %>
        <%= render(partial: 'heliosystem/partials/universeAdminNavActions') if current_universe.owner == current_user %>
      <% end %>
    <% else %>
      <%= action_link new_universe_path, '<i class="fas fa-plus-circle"></i>', 'Create a New Universe', '#f06' %>
    <% end %>
    <%= render(partial: 'heliosystem/partials/sysopNavActions') if current_user.sysop %>
  </section>
<% end %>

app/views/heliosystem/partials/_customFormFields.html.erb
<%= form.simple_fields_for :subfield_values do |sf| %>
  <% current_universe.subfields.where(app: app).each do |field| %>
    <%= sf.input field.label, as: field.format, required: false, include_blank: true, input_html: {value: model.subfield_values.find_by(subfield_id: field.id)&.value} %>
  <% end %>
<% end %>
<%= form.simple_fields_for :subrelation_pairs do |sr| %>
  <% current_universe.subrelations.where(parent: app).each do |field| %>
    <%= sr.input field.label, as: (field.format == 'one-to-one' ? :radio_buttons : :check_boxes), required: false, include_blank: true, collection: current_universe.send(field.child.pluralize.to_sym).all, checked: field.subrelation_pairs.map{|p| p.child_id} %>
  <% end %>
<% end %>

app/views/heliosystem/partials/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
  <%= link_to root_path, class: 'navbar-brand' do %><%= image_tag 'heliosystem/heliosystem-inverse.png' %><% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <% breadcrumbs.each do |link, label| %>
          <li class="navbar-text">
            <i class="fas fa-chevron-right"></i>
          </li>
          <li class="nav-item">
            <%= link_to label, link, class: 'nav-link' %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if flash.empty? %>
        <li class="navbar-text">
          <i class="fas fa-bell"></i> &nbsp; &nbsp;
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            (<%= flash.count %>) &nbsp; <i class="fas fa-bell"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right flash-dropdown" aria-labelledby="navbarDropdown">
            <% flash.each do |k, msg| %>
              <div class="alert alert-dark">
                <%= msg %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user %>
            <i class="fas fa-user"></i>
          <% else %>
            <i class="far fa-user-circle"></i>
          <% end %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign Out', destroy_session_path, class: 'dropdown-item' %>
          <% else %>
            <%= link_to 'Sign Up', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/heliosystem/partials/_orgAppsNavActions.html.erb
<%= action_link [current_universe, current_organization], icon('tachometer-alt'), "#{current_organization.name} Dashboard", current_organization.color %>
<%= action_link universe_organization_people_path(current_organization, universe_id: current_universe.slug), icon('user-friends'), "People", current_organization.color %>

<%= action_link universe_organization_accounts_path(current_organization, universe_id: current_universe.slug), icon('dollar-sign'), "Accounts", current_organization.color if current_organization.accounts_enabled %>
<%= action_link universe_organization_pages_path(current_organization, universe_id: current_universe.slug), icon('copy'), "Pages", current_organization.color if current_organization.pages_enabled %>
<%= action_link universe_organization_timeclocks_path(current_organization, universe_id: current_universe.slug), icon('user-clock'), "TimeClocks", current_organization.color if current_organization.timeclocks_enabled %>

<%= action_link universe_organization_tags_path(current_organization, universe_id: current_universe.slug), icon('tags'), "Tags", current_organization.color %>

<% if current_person.admin || current_person.user.sysop %>
<%= modal_action_button 'organizationAdminModal', icon('wrench'), "#{current_organization.name} Administration", current_organization.color %>
  <% content_for :modals do %>
    <div class="modal fade" id="organizationAdminModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title"><%= current_organization.name %> Administration</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col">
                <p><%= link_to "#{current_organization.name} Setup", edit_universe_organization_path(current_organization, universe_id: current_universe.slug) %></p>
                <p><%= link_to "Organization Settings", universe_organization_settings_path(current_organization, universe_id: current_universe.slug) %></p>
              </div>
              <div class="col">

              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/heliosystem/partials/_sysopNavActions.html.erb
<%= modal_action_button 'debuggerModal', icon('bug'), 'Debug Info', '#666' %>
<% content_for :modals do %>
  <div class="modal fade" id="debuggerModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Debugging Info</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <h3>params</h3>
          <table class="table table-striped">
            <% params.each do |k,v| %>
              <tr>
              <td><%= k %></td>
              <td><%= v.to_json %></td>
              </tr>
            <% end %>
          </table>
          <h3>breadcrumbs</h3>
          <table class="table table-striped">
            <% breadcrumbs.each do |k| %>
              <tr>
              <td><%= k[0] %></td>
              <td><%= k[1] %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/heliosystem/partials/_taggableFormFields.html.erb
<%= form.association :tags, as: :check_boxes, collection: (current_organization ? current_organization.tags : current_universe.top_level_tags) %>

app/views/heliosystem/partials/_universeAdminNavActions.html.erb
<%= modal_action_button 'universeAdminModal', icon('tools'), 'Universe Administration', current_universe.color %>
<% content_for :modals do %>
  <div class="modal fade" id="universeAdminModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Universe Administration</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col">
              <p><%= link_to "Universe Setup", edit_universe_path(current_universe) %></p>
              <p><%= link_to "Universe Settings", universe_settings_path(current_universe) %></p>
              <p><%= link_to "Organizations Manager", universe_organizations_path(current_universe) %></p>
            </div>
            <div class="col">
              <p><%= link_to "Custom Field Setup", universe_subfields_path(current_universe) %></p>
              <p><%= link_to "Custom Relationship Setup", universe_subrelations_path(current_universe) %></p>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>